[options]
admin_passwd = $pbkdf2-sha512$600000$19r73/vfuzdmrDUmJESIMQ$Zh97JPHGm447el35thixMvTDur9v0b4KxaOX1/YnT/BVbpvo1xz05iRC3.87/mjLJc26AdyDXfIynDpv4fSpOw
addons_path = /Users/raffael/Projekte/PrivateMind/odoo/community/addons, /Users/raffael/Projekte/PrivateMind/odoo/reporting-engine,/Users/raffael/Projekte/PrivateMind/odoo/web, /Users/raffael/Projekte/PrivateMind/odoo/svn_orbitpdf-18, /Users/raffael/Projekte/PrivateMind/odoo/theme_liquid_glass, /Users/raffael/Projekte/PrivateMind/odoo/addons/18.0
db_name = odoo
db_host = localhost
db_port = 54321
db_user = odoo
db_password = odoo
data_dir = /Users/raffael/Projekte/odoo/home
list_db = True
proxy_mode = False
db_maxconn = 100
max_cron_threads = 2
max_connections = 1000
session_timeout = 60
session_gc = 60
sessions.max_inactivity_seconds = 60

[sessions]
max_inactivity_seconds = 60

 